apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress-lb-leo
  annotations:
    #app.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "api.asianmomrecipes.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recipe-service
            port:
              number: 50150
  - host: "api.delrosamassage.co"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: massage-service
            port:
              number: 65535
  ingressClassName: nginx
